INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (1, '02', 'Entrada Confirmada (verificar motivo na posição 319 a 328)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (2, '03', 'Entrada Rejeitada (verificar motivo na posição 319 a 328)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (3, '06', 'Liquidação normal (sem motivo)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (4, '09', 'Baixado Automat. via Arquivo (verificar motivo posição 319 a 328)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (5, '10', 'Baixado conforme instruções da Agência(verificar motivo pos.319 a 328)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (6, '11', 'Em Ser - Arquivo de Títulos pendentes (sem motivo)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (7, '12', 'Abatimento Concedido (sem motivo)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (8, '13', 'Abatimento Cancelado (sem motivo)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (9, '14', 'Vencimento Alterado (sem motivo)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (10, '15', 'Liquidação em Cartório (sem motivo)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (11, '16', 'Título Pago em Cheque – Vinculado');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (12, '17', 'Liquidação após baixa ou Título não registrado (sem motivo)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (13, '18', 'Acerto de Depositária (sem motivo)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (14, '19', 'Confirmação Receb. Inst. de Protesto (verificar motivo pos.295 a 295)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (15, '20', 'Confirmação Recebimento Instrução Sustação de Protesto (sem motivo)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (16, '21', 'Acerto do Controle do Participante (sem motivo)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (17, '22', 'Título Com Pagamento Cancelado');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (18, '23', 'Entrada do Título em Cartório (sem motivo)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (19, '24', 'Entrada rejeitada por CEP Irregular (verificar motivo pos.319 a 328)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (20, '25', 'Confirmação Receb.Inst.de Protesto Falimentar (verificar pos.295 a 295)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (21, '27', 'Baixa Rejeitada (verificar motivo posição 319 a 328)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (22, '28', 'Débito de tarifas/custas (verificar motivo na posição 319 a 328)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (23, '29', 'Ocorrências do Pagador');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (24, '30', 'Alteração de Outros Dados Rejeitados (verificar motivo pos.319 a 328)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (25, '32', 'Instrução Rejeitada (verificar motivo posição 319 a 328)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (26, '33', 'Confirmação Pedido Alteração Outros Dados (sem motivo)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (27, '34', 'Retirado de Cartório e Manutenção Carteira (sem motivo)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (28, '35', 'Desagendamento do débito automático (verificar motivos pos. 319 a 328) 46/57');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (29, '40', 'Estorno de pagamento');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (30, '55', 'Sustado judicial');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (31, '68', 'Acerto dos dados do rateio de Crédito (verificar motivo posição de status do registro tipo 3)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (32, '69', 'Cancelamento dos dados do rateio (verificar motivo posição de status do registro tipo 3)');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (33, '73', 'Confirmação Receb. Pedido de Negativação');
INSERT INTO carteira_pesca.ocorrencia (id, codigo, descricao) VALUES (34, '74', 'Confir Pedido de Excl de Negat (com ou sem baixa)');

INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (1, '00', 'Ocorrência aceita');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (2, '00', 'Título pago com dinheiro');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (3, '00', 'Baixado Conforme Instruções da Agência');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (4, '00', 'Título pago com dinheiro');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (5, '01', 'Código do Banco inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (6, '02', 'Código do registro detalhe inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (7, '02', 'Tarifa de permanência título cadastrado (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (8, '03', 'Código da ocorrência inválida');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (9, '03', 'Tarifa de sustação/Excl Negativação (ALTERADO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (10, '04', 'Código de ocorrência não permitido para a carteira');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (11, '04', 'Tarifa de protesto/Incl Negativação (ALTERADO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (12, '04', 'Código de ocorrência não permitido para a carteira');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (13, '05', 'Código de ocorrência não numérico');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (14, '05', 'Tarifa de outras instruções (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (15, '05', 'Código de ocorrência não numérico');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (16, '06', 'Tarifa de outras ocorrências (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (17, '07', 'Agência/Conta/dígito inválidos');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (18, '08', 'Nosso número inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (19, '08', 'Custas de protesto');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (20, '08', 'Nosso número inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (21, '09', 'Nosso número duplicado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (22, '10', 'Carteira inválida');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (23, '10', 'Caixa Comandada pelo cliente');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (24, '10', 'Carteira inválida');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (25, '12', 'Tarifa de registro (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (26, '13', 'Identificação da emissão do bloqueto inválida');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (27, '13', 'Tarifa título pago no Bradesco (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (28, '14', 'Título Protestado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (29, '14', 'Tarifa título pago compensação (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (30, '15', 'Características da cobrança incompatíveis');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (31, '15', 'Título excluído');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (32, '15', 'Título pago com cheque ');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (33, '15', 'Carteira/Agência/Conta/nosso número inválidos');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (34, '15', 'Tarifa título baixado não pago (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (35, '15', 'Características da cobrança incompatíveis');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (36, '16', 'Título Baixado pelo Banco por decurso Prazo ');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (37, '16', 'Tarifa alteração de vencimento (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (38, '16', 'Data de vencimento inválida');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (39, '17', 'Data de vencimento anterior a data de emissão');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (40, '17', 'Titulo Baixado Transferido Carteira');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (41, '17', 'Tarifa concessão abatimento (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (42, '17', 'Data de vencimento anterior a data de emissão');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (43, '18', 'Vencimento fora do prazo de operação 49/57');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (44, '18', 'pagamento Parcial');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (45, '18', 'Tarifa cancelamento de abatimento (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (46, '18', 'Vencimento fora do prazo de operação');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (47, '19', 'Tarifa concessão desconto (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (48, '20', 'Valor do Título inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (49, '20', 'Titulo Baixado e Transferido para Desconto');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (50, '20', 'Tarifa cancelamento desconto (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (51, '20', 'Valor do título inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (52, '21', 'Espécie do Título inválida');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (53, '21', 'Tarifa título pago cics (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (54, '22', 'Espécie não permitida para a carteira');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (55, '22', 'Tarifa título pago Internet (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (56, '22', 'Espécie não permitida para a carteira');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (57, '23', 'Tarifa título pago term. gerencial serviços (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (58, '24', 'Data de emissão inválida');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (59, '24', 'Tarifa título pago Pág-Contas (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (60, '25', 'Tarifa título pago Fone Fácil (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (61, '26', 'Tarifa título Déb. Postagem (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (62, '26', 'Código de juros de mora inválido (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (63, '27', 'Valor/taxa de juros mora inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (64, '27', 'Tarifa impressão de títulos pendentes (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (65, '27', 'Valor/taxa de juros de mora inválido (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (66, '28', 'Código do desconto inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (67, '28', 'Tarifa título pago BDN (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (68, '28', 'Código de desconto inválido (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (69, '28', 'Código de desconto via Telebradesco inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (70, '29', 'Tarifa título pago Term. Multi Função (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (71, '29', 'Valor do desconto maior/igual ao valor do Título');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (72, '30', 'Impressão de títulos baixados (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (73, '30', 'Desconto a conceder não confere');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (74, '31', 'Impressão de títulos pagos (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (75, '31', 'Concessão de desconto já existente ( Desconto anterior ) 53/57');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (76, '31', 'Concessão de desconto - Já existe desconto anterior');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (77, '32', 'Tarifa título pago Pagfor (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (78, '32', 'Valor do IOF inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (79, '33', 'Tarifa reg/pgto– guichê caixa (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (80, '33', 'Valor do abatimento inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (81, '34', 'Tarifa título pago retaguarda (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (82, '34', 'Valor do abatimento maior/igual ao valor do Título');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (83, '35', 'Tarifa título pago Subcentro (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (84, '36', 'Tarifa título pago Cartão de Crédito (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (85, '36', 'Concessão abatimento - Já existe abatimento anterior');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (86, '37', 'Tarifa título pago Comp Eletrônica (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (87, '38', 'Prazo para protesto/ Negativação inválido (ALTERADO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (88, '38', 'Tarifa título Baix. Pg. Cartório (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (89, '38', 'Prazo para protesto/ Negativação inválido (ALTERADO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (90, '39', 'Tarifa título baixado acerto BCO (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (91, '39', 'Pedido para protesto/ Negativação não permitido para o título (ALTERADO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (92, '40', 'Título com ordem de protesto emitido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (93, '40', 'Baixa registro em duplicidade (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (94, '40', 'Título com ordem/pedido de protesto/Negativação emitido (ALTERADO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (95, '41', 'Tarifa título baixado decurso prazo (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (96, '41', 'Pedido de sustação/excl p/ Título sem instrução de protesto/Negativação (ALTERADO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (97, '42', 'Rateio não efetuado, cód. Calculo 2 (VLR. Registro) e v ');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (98, '42', 'Código para baixa/devolução via Tele Bradesco inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (99, '42', 'Tarifa título baixado Judicialmente (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (100, '43', 'Prazo para baixa e devolução inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (101, '43', 'Tarifa título baixado via remessa (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (102, '44', 'Agência Beneficiário não prevista');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (103, '44', 'Tarifa título baixado rastreamento (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (104, '45', 'Nome do Pagador inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (105, '45', 'Nome do pagador não informado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (106, '45', 'Tarifa título baixado conf. Pedido (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (107, '45', 'Nome do Pagador não informado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (108, '46', 'Tipo/num. de inscrição do Pagador inválidos');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (109, '46', 'Tipo/número de inscrição do pagador inválidos');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (110, '46', 'Tarifa título baixado protestado (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (111, '46', 'Tipo/número de inscrição do Pagador inválidos');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (112, '47', 'Endereço do pagador não informado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (113, '47', 'Tarifa título baixado p/ devolução (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (114, '47', 'Endereço do Pagador não informado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (115, '48', 'CEP inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (116, '48', 'Tarifa título baixado franco pagto (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (117, '49', 'Tarifa título baixado SUST/RET/CARTÓRIO (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (118, '50', 'CEP referente a Banco correspondente');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (119, '50', 'CEP irregular - Banco Correspondente');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (120, '50', 'Tarifa título baixado SUS/SEM/REM/CARTÓRIO (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (121, '50', 'CEP referente a um Banco correspondente');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (122, '51', 'Tarifa título transferido desconto (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (123, '52', 'Cobrado baixa manual (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (124, '53', 'Nº de inscrição do Pagador/avalista inválidos (CPF/CNPJ)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (125, '53', 'Baixa por acerto cliente (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (126, '53', 'Tipo/Número de inscrição do pagador/avalista inválidos (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (127, '53', 'Tipo de inscrição do pagador avalista inválidos');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (128, '54', 'Pagador/avalista não informado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (129, '54', 'Tarifa baixa por contabilidade (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (130, '55', 'Tr. tentativa cons deb aut56..Tr. credito online');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (131, '57', 'Tarifa reg/pagto Bradesco Expresso');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (132, '57', 'Código da multa inválido (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (133, '58', 'Tarifa emissão Papeleta (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (134, '58', 'Data da multa inválida (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (135, '59', 'Tarifa fornec papeleta semi preenchida (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (136, '60', 'Movimento para Título não cadastrado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (137, '60', 'Acondicionador de papeletas (RPB)S (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (138, '60', 'Movimento para Título não cadastrado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (139, '61', 'Acond. De papelatas (RPB)s PERSONAL (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (140, '62', 'Papeleta formulário branco (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (141, '63', 'Entrada para Título já cadastrado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (142, '63', 'Formulário A4 serrilhado (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (143, '64', 'Fornecimento de softwares transmiss (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (144, '65', 'Limite excedido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (145, '65', 'Fornecimento de softwares consulta (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (146, '66', 'Número autorização inexistente');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (147, '66', 'Fornecimento Micro Completo (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (148, '67', 'Débito automático agendado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (149, '67', 'Fornecimento MODEN (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (150, '68', 'Débito não agendado - erro nos dados de remessa');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (151, '68', 'Fornecimento de máquina FAX (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (152, '69', 'Débito não agendado - Pagador não consta no cadastro de autorizante');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (153, '69', 'Fornecimento de máquinas óticas (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (154, '70', 'Débito não agendado - Beneficiário não autorizado pelo Pagador');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (155, '70', 'Fornecimento de Impressoras (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (156, '71', 'Débito não agendado - Beneficiário não participa do débito Automático');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (157, '71', 'Reativação de título (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (158, '72', 'Débito não agendado - Código de moeda diferente de R$');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (159, '72', 'Alteração de produto negociado (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (160, '73', 'Débito não agendado - Data de vencimento inválida/vencida');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (161, '73', 'Tarifa emissão de contra recibo (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (162, '74', 'Débito não agendado - Conforme seu pedido, Título não registrado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (163, '74', 'Tarifa emissão 2ª via papeleta (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (164, '75', 'Débito não agendado - Tipo do número de inscrição do pagador debitado inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (165, '75', 'Débito não agendado – Tipo de número de inscrição do debitado inválido ');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (166, '75', 'Tarifa regravação arquivo retorno (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (167, '76', 'Pagador Eletrônico DDA - Esse motivo somente será disponibilizado no arquivo retorno para as empresas cadastradas nessa condição.');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (168, '76', 'Arq. Títulos a vencer mensal (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (169, '77', 'Transferência para desconto não permitido para a carteira');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (170, '77', 'Listagem auxiliar de crédito (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (171, '78', 'Tarifa cadastro cartela instrução permanente (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (172, '78', 'Pagador alega que faturamento e indevido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (173, '79', 'Canalização de Crédito (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (174, '79', 'Data de Juros de mora Inválida (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (175, '80', 'Cadastro de Mensagem Fixa (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (176, '80', 'Data do desconto inválida (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (177, '81', 'Tarifa reapresentação automática título (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (178, '81', 'Tentativas esgotadas, baixado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (179, '82', 'Tarifa registro título déb. Automático (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (180, '82', 'Tentativas esgotadas, pendente');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (181, '83', 'Tarifa Rateio de Crédito (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (182, '83', 'Cancelado pelo Pagador e Mantido Pendente, conforme negociação (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (183, '84', 'Emissão papeleta sem valor (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (184, '84', 'Cancelado pelo pagador e baixado, conforme negociação (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (185, '85', 'Título com pagamento vinculado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (186, '85', 'Sem uso (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (187, '85', 'Título com pagamento vinculado');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (188, '86', 'Seu número do documento inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (189, '86', 'Cadastro de reembolso de diferença (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (190, '86', 'Seu número inválido');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (191, '87', 'Relatório fluxo de pagto (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (192, '88', 'Emissão Extrato mov. Carteira (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (193, '88', 'E-mail Pagador não lido no prazo 5 dias (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (194, '89', 'Email Pagador não enviado – título com débito automático');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (195, '89', 'Mensagem campo local de pagto (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (196, '90', 'Email pagador não enviado – título de cobrança sem registro ');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (197, '90', 'Cadastro Concessionária serv. Publ. (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (198, '91', 'Classif. Extrato Conta Corrente (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (199, '91', 'E-mail pagador não recebido (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (200, '92', 'Contabilidade especial (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (201, '93', 'Realimentação pagto (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (202, '94', 'Repasse de Créditos (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (203, '94', 'Título Penhorado – Instrução Não Liberada pela Agência (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (204, '95', 'Pagador aceita/reconhece o faturamento');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (205, '96', 'Tarifa reg. Pagto outras mídias (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (206, '97', 'Tarifa Reg/Pagto – Net Empresa (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (207, '97', 'Instrução não permitida título negativado (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (208, '98', 'Tarifa título pago vencido (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (209, '98', 'Inclusão Bloqueada face a determinação Judicial (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (210, '99', 'TR Tít. Baixado por decurso prazo (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (211, '99', 'Telefone beneficiário não informado / inconsistente (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (212, '100', 'Arquivo Retorno Antecipado (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (213, '101', 'Arq retorno Hora/Hora (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (214, '102', 'TR. Agendamento Déb Aut (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (215, '105', 'TR. Agendamento rat. Crédito (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (216, '106', 'TR Emissão aviso rateio (NOVO)');
INSERT INTO carteira_pesca.motivo_ocorrencia (id, codigo, descricao) values (217, '107', 'Extrato de protesto (NOVO)');
