export const SET_SOLICITANTE = "SET_SOLICITANTE";
export const SET_ERROR = "SET_ERROR";
export const SET_MUNICIPIOS = "SET_MUNICIPIOS";
export const SET_UFS = "SET_UFS";
export const ACTIVE_CADASTRO = "ACTIVE_CADASTRO";
export const DESACTIVE_CADASTRO = "DESACTIVE_CADASTRO";
