server:
  port: 9666

logging:
  level:
    br.ufla.lemaf.ti: INFO
    org.hibernate: ERROR
  file: /var/log/application/carteira_pesca.log

spring:

  application:
    name: Sistema de emissão de Licença de Pesca
    urlBase: http://localhost:9666/
    urBaseAutenticacao: http://localhost:8080/listagem-remessas

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  datasource:
    platform: postgres
    url: jdbc:postgresql://runners.ti.lemaf.ufla.br:5432/carteira_pesca
    username: carteira_pesca
    password: carteira_pesca

  jpa:
    properties:

      hibernate:
        show_sql: false
        format_sql: false
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        ddl-auto: validate

  flyway:
    enabled: false
    baseline-on-migrate: false

  jackson:
    time-zone: UTC
    locale: pt_BR

  security:
    fakeAuthentication: false
    successRedirectUrl: http://localhost:8080/listagem-remessa
    ipsAllowed: 127.0.0.1,::1

    entradaUnica:
      # Módulo - RUNNERS
      client-id: c6d78ffb11a81a8bad0b0f2d0c74fb1e61a71347d9dc57dc63dc9748c987e2c2472ce51a21d42a433a0469a901ece061e8d0eeb2f6de65c513f9921067276d72
      client-secret: 1e29b8683d462d6bd93689e567c337131eeef2ac8f9b200695d9cda50a124663a694009f24c7b29c46a2a09f0eab4037416f32882becc0059bcaf4132675371d

      portal-seguranca:
        url: http://am.runners.ti.lemaf.ufla.br/portal-seguranca
      cadastro-unificado:
        url: http://am.runners.ti.lemaf.ufla.br/cadastro-unificado

  carteira-pesca:
    base-path: arquivos/carteira/

  arquivos:
    base-path-arquivos-dados: src/main/resources/gerador/
    temporario: /tmp/

  gestao-pagamentos:
    codigo-modulo: LICENCA_PESCA
    codigo-beneficiario: IPAAM
    url: http://am.runners.ti.lemaf.ufla.br/gestao-pagamentos
