server:
  port: 9666

logging:
  level:
    br.ufla.lemaf.ti: ERROR
    org.hibernate: ERROR
  file: /dados/logs/carteira-pesca/carteira_pesca.log

spring:

  application:
    urlBase: http://sistemas.ipaam.am.gov.br/carteira-pesca/
    name: Glide
    version: @project.version@

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.100.29:5432/carteira_pesca
    username: carteira_pesca
    password: carteira_pesca

  jpa:
    properties:

      hibernate:
        show_sql: false
        format_sql: false
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        ddl-auto: validate

  flyway:
    enabled: false

  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  security:
    fakeAuthentication: false
    successRedirectUrl: /

    entradaUnica:
      client-id: 7212ad07d6da519b0d95fd94d2e2b62a2443f1aae07b95a8aa3b1b5b3a84bc5dc981305a2a905474f2eaa5e7c6b84a924f08b28476ffddaba8db4eefccebdbe3
      client-secret: 0a940507425458e7714c3c7c6abbaf1b149ddcd1245f6620de0e658b40183beb3d10316e8bb5e9c383ec299fa95e2cbf3ef62d7d192a4bdcd34e1ceb2cda2bf3
      portal-seguranca:
        url: http://sistemas.ipaam.am.gov.br/portal-seguranca/
      cadastro-unificado:
        url: http://sistemas.ipaam.am.gov.br/cadastro-unificado

  carteira-pesca:
    base-path: /dados/carteira-pesca/carteira/
    path-arquivo-boleto: /dados/carteira-pesca/boleto/
    path-arquivo-remessa: /dados/carteira-pesca/remessa/
    path-arquivo-retorno: /dados/carteira-pesca/retorno/



