server:
  port: 9902

logging:
  level:
    br.ufla.lemaf.ti: DEBUG
    org.hibernate: DEBUG
  file: /var/spring/logs/carteira-pesca/carteira_pesca.log

spring:

  application:
    name: Sistema de emissão de Licença de Pesca
    urlBase: http://am.runners.ti.lemaf.ufla.br/carteira-pesca/

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  datasource:
    platform: postgres
    url: jdbc:postgresql://runners.ti.lemaf.ufla.br:5432/carteira_pesca
    username: carteira_pesca
    password: carteira_pesca

  jpa:
    properties:

      hibernate:
        show_sql: true
        format_sql: true
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        ddl-auto: validate

  flyway:
    outOfOrder: true
    baseline-on-migrate: true
    enabled: false

  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  security:

    fakeAuthentication: false
    successRedirectUrl: /

    entradaUnica:
      # Módulo - RUNNERS
      client-id: c6d78ffb11a81a8bad0b0f2d0c74fb1e61a71347d9dc57dc63dc9748c987e2c2472ce51a21d42a433a0469a901ece061e8d0eeb2f6de65c513f9921067276d72
      client-secret: 1e29b8683d462d6bd93689e567c337131eeef2ac8f9b200695d9cda50a124663a694009f24c7b29c46a2a09f0eab4037416f32882becc0059bcaf4132675371d

      portal-seguranca:
        url: http://am.runners.ti.lemaf.ufla.br/portal-seguranca
      cadastro-unificado:
        url: http://am.runners.ti.lemaf.ufla.br/cadastro-unificado

  carteira-pesca:
    base-path: var/dados/amazonas/arquivos/carteira-pesca/carteira/
    path-arquivo-boleto: var/dados/amazonas/arquivos/carteira-pesca/boleto/
    path-arquivo-remessa: var/dados/amazonas/arquivos/carteira-pesca/remessa/
    path-arquivo-retorno: var/dados/amazonas/arquivos/carteira-pesca/retorno/
    path-arquivo-retorno-disponibilizado-banco: var/dados/amazonas/dadosWebTA/Retorno/
