server:
  port: 9666

logging:
  level:
    br.ufla.lemaf.ti: DEBUG
    org.hibernate: DEBUG
  file: /var/log/application/carteira_pesca.log

spring:

  application:
    name: Sistema de emissão de Licença de Pesca

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/carteira_pesca
    username: carteira_pesca
    password: carteira_pesca

  jpa:
    properties:

      hibernate:
        show_sql: true
        format_sql: true
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true

  jackson:
    time-zone: UTC
    locale: pt_BR

  security:
    entradaUnica:
      cliente-id: 669517306c170afbb057af56d8c7237d3bd7cc3c88abb6786b6288a670fb37acdac2125a78f36643069079427c735600c0fc1eb872322eb7a1b85eb30aa18e22
      cliente-secret: 9aed47e0a741ba1e2f15db134e5aaf8fe2bcb67b714ff4be9bd64e7823af06526895b21a732218ad9867e85425e34e4f8e70297dd468dce69669f418d22a31ec
      portal-seguranca:
        url: http://java1.pa.ti.lemaf.ufla.br
      cadastro-unificado:
        url: http://java1.pa.ti.lemaf.ufla.br/cadastroUnificado
