server:
  port: 9666

logging:
  level:
    br.ufla.lemaf.ti: INFO
    org.hibernate: ERROR
  file: /var/log/application/carteira_pesca.log

spring:

  application:
    name: Sistema de emissão de Licença de Pesca
    urlBase: http://localhost:9666/
    urBaseAutenticacao: http://localhost:8080/listagem-remessas

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/carteira_pesca_ap
    username: carteira_pesca
    password: carteira_pesca

  jpa:
    properties:

      hibernate:
        show_sql: false
        format_sql: false
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        ddl-auto: validate

  flyway:
    enabled: false
    baseline-on-migrate: false

  jackson:
    time-zone: UTC
    locale: pt_BR

  security:
    fakeAuthentication: false
    successRedirectUrl: http://localhost:8080/listagem-remessa
    ipsAllowed: 127.0.0.1,::1

    entradaUnica:
      # Módulo - PUMA
      client-id: 2994fd5c58de22ac4451638586441c6d6729bc0c2b0c9993f91dfda8d62dc00d47d0097636930f9bb4d76ea4b83056532724bdbcaf942c64049be1b6e1633611
      client-secret: 4bafb48e14e76b04e3d4e674722db8022c3510670188e1ff8f4d1d6f0fa44dba7f5bb1ac9929a7e4c6aa018424a097c82d01bd88c98a47d786b24c26d281fd5e

      portal-seguranca:
        url: http://localhost:9900
      cadastro-unificado:
        url: http://localhost:9901

  carteira-pesca:
    base-path: arquivos/carteira/

  arquivos:
    base-path-arquivos-dados: src/main/resources/gerador/
    temporario: /tmp/

  gestao-pagamentos:
    codigo-modulo: LICENCA_PESCA
    codigo-beneficiario: SEMA
    url: http://localhost:9913
