server:
  port: 9902

logging:
  level:
    br.ufla.lemaf.ti: DEBUG
    org.hibernate: DEBUG
  file: /var/spring/logs/carteira-pesca/carteira_pesca.log

spring:

  application:
    name: Sistema de emissão de Licença de Pesca
    urlBase: http://ap.puma.ti.lemaf.ufla.br/carteira-pesca/

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  datasource:
    platform: postgres
    url: jdbc:postgresql://ap.puma.ti.lemaf.ufla.br:5432/carteira_pesca_ap
    username: carteira_pesca
    password: carteira_pesca

  jpa:
    properties:

      hibernate:
        show_sql: true
        format_sql: true
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
        ddl-auto: validate

  flyway:
    outOfOrder: true
    baseline-on-migrate: true
    enabled: false

  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  security:

    fakeAuthentication: false
    successRedirectUrl: /

    entradaUnica:
      # Módulo - RUNNERS
      client-id: 638aea9e01a6c8040a49010e677010eb5fddb42701481aa7eaca7af3b3459fd7637844f0ced5a14fa689b40f1e3d73fbd4f942ab5fb5ee8f925381d8f82da58a
      client-secret: c09b4f67370f2f21fe1574e82f5e0200560ff0fb6c883bc99c698068151d99ffba08f545fc140783e2bd08bc2a196ec7305e112c200942c4435bb38e8a752315

      portal-seguranca:
        url: http://ap.puma.ti.lemaf.ufla.br/portal-seguranca
      cadastro-unificado:
        url: http://ap.puma.ti.lemaf.ufla.br/cadastro-unificado

  carteira-pesca:
    base-path: var/dados/amapa/arquivos/carteira-pesca/carteira/

  gestao-pagamentos:
    codigo-modulo: LICENCA_PESCA
    codigo-beneficiario: SEMA
    url: http://ap.puma.ti.lemaf.ufla.br/gestao-pagamentos
